apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: appsec
  name: security-champion-slackbot
  namespace: appsec
spec:
  image: {{image}}
  ttlSecondsAfterFinished: 300
  schedule: "37 11 * * *"
  gcp:
    buckets:
      - name: security-champion-slackbot
        lifecycleCondition:
          age: 7
          numNewerVersions: 2
          withState: ANY
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
      rules:
      - application: team-catalog-backend
        namespace: org
        cluster: prod-gcp
  envFrom:
    - secret: security-champion-slackbot-config
  env:
    - name: TEAMKATALOG_API_URL
      value: "http://team-catalog-backend.org.svc.cluster.local"
    - name: GSC_BUCKET_NAME
      value: security-champion-slackbot
    - name: NPM_CONFIG_CACHE
      value: /tmp

